---
platform: linux

inputs:
  - name: source

run:
  path: sh
  dir: source
  args:
    - -exc
    - |
      apk add --update bash curl g++ make redis
      redis-server &
      make test
      pkill redis-server