---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: go
    tag: 1.17
    username: ((dockerhub-username))
    password: ((dockerhub-password))

inputs:
  - name: source

run:
  path: make
  dir: source
  args: [test]
